### ISSUE TITLE
Different marks design (left hand, right hand, neutral)

### ISSUE THREAD

**Issue by nicoblabla** [amiguet/harpejjitabs#12]

**Comment by nicoblabla** [comment]
Hello @amiguet 

I'v made some design test for the left and right hand ! (at the bottom of the page)

Could you tell me if any of them is ok and/or what change you'll like to make !

I can try other design too

**Comment by amiguet** [comment]
Thanks @nicoblabla, nice designs! :-)

I think the top row (drop-shaped) shapes look good and are very readable. They might need minor adjustments when they are integrated on the fretboard, but it seems a very good starting point! Go ahead with them!

**Comment by nicoblabla** [comment]
I've pushed the last version !

I haven't think so much about the contextual design for now.
I maybe need to change that, like putting icon instead of text, or make something about this:
![image](https://user-images.githubusercontent.com/7037582/98649804-50764100-2338-11eb-84ca-80cf5f974db6.png)(!!)

There is also some overlapping for 2 marks next to each other with opposite hands

**Comment by amiguet** [comment]
Great! Thank you! :-)

For the contextual menu I think icons would be nice. Maybe they could be aligned above the 3 columns of colors so that it fixes the misalignment at the same time.

Although it shouldn't happen very often, the overlap is definitely not pretty. Maybe by making the "tail" slightly smaller and slightly more upright it's possible to avoid it?

**Comment by amiguet** [comment]
Also, I think I stumbled upon a bug: if I create, say, a "Left" mark at a position, delete it and re-create a mark at this position it defaults to left. Not very intuitive, but there's worse: if I load a file that has a mark in the same position, the mark becomes "left" even if it was saved as neutral.

To say it otherwise: when a mark is deleted, it seems that its shape still remains at this position.

I hope that's clear. If it's not, I can provide a more detailed description and/or .htab files to reproduce.

**Comment by nicoblabla** [comment]
Ah yes, my bad, I haven't made the save / load system to serialize the hand property yet.

For the moment, when you remove a mark, all of its properties remain, (color, number, and hand), Do I need to reset them all, or only some of them ?

**Comment by amiguet** [comment]
I would reset them all. See https://xkcd.com/2109/ ;-)

**Comment by amiguet** [comment]
Regarding overlapping marks: a small overlap might be acceptable, as this is likely to happen only exceptionally. But I think the current one is too big...
